id: PYSEC-0000-CVE-2025-1497
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
details: |-
  A vulnerability, that could result in Remote Code Execution (RCE), has been found in PlotAI. Lack of validation of LLM-generated output allows attacker to execute arbitrary Python code.
  Vendor commented out vulnerable line, further usage of the software requires uncommenting it and thus accepting the risk. The vendor does not plan to release a patch to fix this vulnerability.
affected:
- package:
    name: plotai
    ecosystem: PyPI
    purl: pkg:pypi/plotai
  ranges:
  - type: GIT
    repo: https://github.com/mljar/plotai
    events:
    - introduced: "0"
    - fixed: bdcfb13484f0b85703a4c1ddfd71cb21840e7fde
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 0.0.7
references:
- type: FIX
  url: https://github.com/mljar/plotai/commit/bdcfb13484f0b85703a4c1ddfd71cb21840e7fde
- type: WEB
  url: https://cert.pl/en/posts/2025/03/CVE-2025-1497
- type: WEB
  url: https://cert.pl/posts/2025/03/CVE-2025-1497
- type: WEB
  url: https://github.com/mljar/plotai
aliases:
- CVE-2025-1497
modified: "2025-03-24T18:46:13Z"
published: "2025-03-10T14:15:24Z"
